"""Builds install/InstallKatanaSkills.lua: one paste into the Studio command
bar installs the katana skills (Lumen Rush, Moonfall Crescent) into the
open place. Only the scripts this feature touches are written; Effects,
PoseAnimator, HeadDrive, the HUD and everything else are left alone.

    python3 tools/katana/build_installer.py
"""
import os

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
SRC = os.path.join(ROOT, "src")
OUT = os.path.join(ROOT, "install", "InstallKatanaSkills.lua")

# (name, class, home, parent module or None, source path)
SCRIPTS = [
    ("Config", "ModuleScript", "combat", None, "ReplicatedStorage/Combat/Config.luau"),
    ("Motion", "ModuleScript", "combat", None, "ReplicatedStorage/Combat/Motion.luau"),
    ("AnimationData", "ModuleScript", "combat", None, "ReplicatedStorage/Combat/AnimationData.luau"),
    ("KatanaSkillAnimations", "ModuleScript", "combat", None, "ReplicatedStorage/Combat/KatanaSkillAnimations/init.luau"),
    ("KatanaSkillPoses", "ModuleScript", "combat", "KatanaSkillAnimations", "ReplicatedStorage/Combat/KatanaSkillAnimations/KatanaSkillPoses.luau"),
    ("KatanaFX", "ModuleScript", "combat", None, "ReplicatedStorage/Combat/KatanaFX/init.luau"),
    ("KatanaFXData", "ModuleScript", "combat", "KatanaFX", "ReplicatedStorage/Combat/KatanaFX/KatanaFXData.luau"),
    ("CombatService", "ModuleScript", "server", None, "ServerScriptService/CombatService.luau"),
    ("CombatServer", "Script", "server", None, "ServerScriptService/CombatServer.server.luau"),
    ("CombatClient", "LocalScript", "client", None, "StarterPlayerScripts/CombatClient.client.luau"),
]

HEADER = '''-- Katana skills installer (Z: Lumen Rush, X: Moonfall Crescent).
-- Paste this whole file into Studio's command bar (View > Command Bar) and
-- press Enter. It updates the combat scripts this feature touches, adds the
-- KatanaFX and KatanaSkillAnimations modules, and is a single undo step
-- (Ctrl+Z reverts it). Effects, PoseAnimator, HeadDrive, the HUD and the
-- dummies are not touched.
-- Generated by tools/katana/build_installer.py from src/ - edit those, not this.

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")
local StarterPlayer = game:GetService("StarterPlayer")

local SOURCES = {}
'''

BODY = '''
local SCRIPTS = {
%s
}

local recording
pcall(function()
	recording = ChangeHistoryService:TryBeginRecording("Install katana skills")
end)

local log = {}

-- Writes `source` into parent[name], keeping the existing instance when it's
-- already the right kind of script.
local function put(parent, className, name, source)
	local existing = parent:FindFirstChild(name)
	local fits = existing and (if className == "ModuleScript"
		then existing:IsA("ModuleScript")
		else existing:IsA("BaseScript"))
	if existing and not fits then
		existing.Name = name .. "_Old"
		table.insert(log, "renamed unexpected " .. existing.ClassName .. " to " .. existing:GetFullName())
		existing = nil
	end
	local script = existing or Instance.new(className)
	script.Name = name
	script.Source = source
	script.Parent = parent
	table.insert(log, (existing and "updated " or "created ") .. script:GetFullName())
	return script
end

local combat = ReplicatedStorage:FindFirstChild("Combat")
assert(combat, "ReplicatedStorage.Combat not found: install the combat system first")
for _, needed in ipairs({ "PoseAnimator", "Effects", "CameraFX", "Hitbox", "HeadDrive", "KatanaAnimations" }) do
	if not combat:FindFirstChild(needed) then
		warn("ReplicatedStorage.Combat." .. needed .. " is missing; the katana skills expect it")
	end
end

local existingService = ServerScriptService:FindFirstChild("CombatService", true)
local serverHome = existingService and existingService.Parent or ServerScriptService
local existingClient = StarterPlayer:FindFirstChild("CombatClient", true)
local clientHome = existingClient and existingClient.Parent
	or StarterPlayer:FindFirstChildOfClass("StarterPlayerScripts")
	or StarterPlayer:WaitForChild("StarterPlayerScripts")
local HOMES = { combat = combat, server = serverHome, client = clientHome }

-- Keep the sprite ids already pasted into this place's Config.KatanaTextures
-- (the new Config ships with empty slots).
do
	local current = combat:FindFirstChild('Config')
	local old = current and current:IsA('ModuleScript') and current.Source or ''
	local block = old:match('Config%%.KatanaTextures%%s*=%%s*(%%b{})')
	if block and SOURCES.Config then
		local kept = 0
		for name, id in block:gmatch('([%%w_]+)%%s*=%%s*"(rbxassetid://%%d+)"') do
			local before = SOURCES.Config
			SOURCES.Config = SOURCES.Config:gsub('(Config%%.KatanaTextures%%s*=%%s*%%b{})', function(newBlock)
				return (newBlock:gsub('(%%f[%%w_]' .. name .. '%%s*=%%s*)"[^"]*"', '%%1"' .. id .. '"'))
			end)
			if SOURCES.Config ~= before then
				kept += 1
			end
		end
		table.insert(log, 'kept ' .. kept .. ' sprite ids from your Config.KatanaTextures')
	end
end

local made = {}
for _, entry in ipairs(SCRIPTS) do
	local parent = entry.parent and made[entry.parent] or HOMES[entry.home]
	made[entry.name] = put(parent, entry.class, entry.name, SOURCES[entry.name])
end

if recording then
	ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
else
	pcall(function()
		ChangeHistoryService:SetWaypoint("Install katana skills")
	end)
end

print("Katana skills installed (Z: Lumen Rush, X: Moonfall Crescent, katana drawn):")
for _, line in ipairs(log) do
	print("  " .. line)
end
'''


def delimiter(sources):
    level = 3
    while any(("]" + "=" * level + "]") in s for s in sources):
        level += 1
    return "=" * level


def main():
    texts = []
    for name, cls, home, parent, path in SCRIPTS:
        with open(os.path.join(SRC, path)) as f:
            texts.append((name, cls, home, parent, f.read()))
    eq = delimiter([t[4] for t in texts])
    parts = [HEADER]
    for name, _, _, _, text in texts:
        # a long bracket drops a leading newline, so add one to keep line 1 intact
        parts.append(f"\nSOURCES.{name} = [{eq}[\n{text}]{eq}]\n")
    rows = []
    for n, c, h, parent, _ in texts:
        p = f'"{parent}"' if parent else "nil"
        rows.append(f'\t{{ name = "{n}", class = "{c}", home = "{h}", parent = {p} }},')
    parts.append(BODY % "\n".join(rows))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("".join(parts))
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
