"""Uploads the katana sprites (assets/katana/*.png) with Roblox Open Cloud and
writes their image ids into Config.KatanaTextures.

    ROBLOX_API_KEY=... python3 tools/katana/upload.py --user 123456
    ROBLOX_API_KEY=... python3 tools/katana/upload.py --group 7890

The API key needs the "asset:read" and "asset:write" scopes (and
"legacy-asset:manage" so the decal's image id can be looked up). Open Cloud
uploads images as Decals; particles and beams need the decal's *image* id,
which this resolves. If that lookup is refused, the decal id is printed:
paste it into any Texture property in Studio and Studio converts it.

The simpler route needs no key: Studio > View > Asset Manager > Bulk Import,
select assets/katana/*.png, then right-click each > Copy ID and paste it
into Config.KatanaTextures.
"""
import argparse
import json
import mimetypes
import os
import re
import sys
import time
import urllib.error
import urllib.request
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
ASSETS = os.path.join(ROOT, "assets", "katana")
CONFIG = os.path.join(ROOT, "src", "ReplicatedStorage", "Combat", "Config.luau")
API = "https://apis.roblox.com"


def request(method, url, key, body=None, headers=None):
    req = urllib.request.Request(url, data=body, method=method)
    req.add_header("x-api-key", key)
    for k, v in (headers or {}).items():
        req.add_header(k, v)
    with urllib.request.urlopen(req, timeout=60) as response:
        return json.loads(response.read().decode() or "{}")


def multipart(fields, file_field, filename, data, content_type):
    boundary = uuid.uuid4().hex
    out = []
    for name, value in fields.items():
        out.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"{name}\"\r\n\r\n{value}\r\n".encode())
    out.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"{file_field}\"; filename=\"{filename}\"\r\nContent-Type: {content_type}\r\n\r\n".encode())
    out.append(data)
    out.append(f"\r\n--{boundary}--\r\n".encode())
    return b"".join(out), f"multipart/form-data; boundary={boundary}"


def upload(path, key, creator):
    name = os.path.splitext(os.path.basename(path))[0]
    meta = {
        "assetType": "Decal",
        "displayName": f"Katana FX {name}",
        "description": "Katana skill sprite (generated by tools/katana/textures.py)",
        "creationContext": {"creator": creator},
    }
    with open(path, "rb") as f:
        body, ctype = multipart({"request": json.dumps(meta)}, "fileContent", os.path.basename(path), f.read(), mimetypes.guess_type(path)[0] or "image/png")
    op = request("POST", f"{API}/assets/v1/assets", key, body, {"Content-Type": ctype})
    for _ in range(30):
        if op.get("done"):
            return op["response"]["assetId"]
        time.sleep(1.5)
        op = request("GET", f"{API}/assets/v1/{op['path']}", key)
    raise RuntimeError(f"upload of {name} did not finish")


def image_of(decal_id, key):
    """A decal's content names its image: <url>...?id=IMAGE</url>."""
    info = request("GET", f"{API}/asset-delivery-api/v1/assetId/{decal_id}", key)
    location = info.get("location")
    if not location:
        return None
    with urllib.request.urlopen(location, timeout=60) as response:
        text = response.read().decode("utf8", "replace")
    m = re.search(r"id=(\d+)", text)
    return m.group(1) if m else None


def write_config(ids):
    with open(CONFIG, encoding="utf8") as f:
        text = f.read()
    for name, asset in ids.items():
        text = re.sub(rf'(\n\t{name} = )"[^"]*"', rf'\1"rbxassetid://{asset}"', text, count=1)
    with open(CONFIG, "w", encoding="utf8") as f:
        f.write(text)


def main():
    ap = argparse.ArgumentParser()
    who = ap.add_mutually_exclusive_group(required=True)
    who.add_argument("--user", help="your Roblox user id")
    who.add_argument("--group", help="a group id to own the images")
    args = ap.parse_args()
    key = os.environ.get("ROBLOX_API_KEY")
    if not key:
        sys.exit("set ROBLOX_API_KEY (Creator Dashboard > Open Cloud > API Keys)")
    creator = {"userId": args.user} if args.user else {"groupId": args.group}
    ids = {}
    for file in sorted(os.listdir(ASSETS)):
        if not file.endswith(".png"):
            continue
        name = file[:-4]
        try:
            decal = upload(os.path.join(ASSETS, file), key, creator)
            image = None
            try:
                image = image_of(decal, key)
            except urllib.error.HTTPError as e:
                print(f"  {name}: decal {decal} (image lookup refused: {e.code}); paste the decal id into a Texture in Studio to convert it")
            if image:
                ids[name] = image
                print(f"  {name}: image {image}")
        except urllib.error.HTTPError as e:
            print(f"  {name}: upload failed ({e.code}) {e.read().decode(errors='replace')[:200]}")
    if ids:
        write_config(ids)
        print(f"wrote {len(ids)} ids into Config.KatanaTextures; rebuild the installer: python3 tools/katana/build_installer.py")


if __name__ == "__main__":
    main()
