"""Builds install/InstallCombat.lua: one paste into the Studio command bar
installs every changed script from src/ into the open place.

    python3 tools/build_installer.py
"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
SRC = os.path.join(ROOT, "src")
OUT = os.path.join(ROOT, "install", "InstallCombat.lua")

# (name, class, home, source path). Dummies is unchanged and left alone.
SCRIPTS = [
    ("AnimationBuilder", "ModuleScript", "combat", "ReplicatedStorage/Combat/AnimationBuilder.luau"),
    ("AnimationData", "ModuleScript", "combat", "ReplicatedStorage/Combat/AnimationData.luau"),
    ("CameraFX", "ModuleScript", "combat", "ReplicatedStorage/Combat/CameraFX.luau"),
    ("Config", "ModuleScript", "combat", "ReplicatedStorage/Combat/Config.luau"),
    ("Effects", "ModuleScript", "combat", "ReplicatedStorage/Combat/Effects.luau"),
    ("Motion", "ModuleScript", "combat", "ReplicatedStorage/Combat/Motion.luau"),
    ("PoseAnimator", "ModuleScript", "combat", "ReplicatedStorage/Combat/PoseAnimator.luau"),
    ("CombatService", "ModuleScript", "server", "ServerScriptService/CombatService.luau"),
    ("CombatServer", "Script", "server", "ServerScriptService/CombatServer.server.luau"),
    ("CombatClient", "LocalScript", "client", "StarterPlayerScripts/CombatClient.client.luau"),
]

HEADER = '''-- Combat rework installer.
-- Paste this whole file into Studio's command bar (View > Command Bar) and
-- press Enter. It overwrites the combat scripts in place, adds CameraFX,
-- removes the old HUD module, and is a single undo step (Ctrl+Z reverts it).
-- Generated by tools/build_installer.py from src/ - edit those, not this.

local ChangeHistoryService = game:GetService("ChangeHistoryService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerScriptService = game:GetService("ServerScriptService")
local StarterPlayer = game:GetService("StarterPlayer")

local SOURCES = {}
'''

BODY = '''
local SCRIPTS = {
%s
}

local recording
pcall(function()
	recording = ChangeHistoryService:TryBeginRecording("Install combat rework")
end)

local log = {}

local function folder(parent, name)
	local existing = parent:FindFirstChild(name)
	if existing then
		return existing
	end
	local new = Instance.new("Folder")
	new.Name = name
	new.Parent = parent
	table.insert(log, "created " .. new:GetFullName())
	return new
end

-- Writes `source` into parent[name], keeping the existing instance (and its
-- RunContext, attributes, etc.) when it's already the right kind of script.
local function put(parent, className, name, source)
	local existing = parent:FindFirstChild(name)
	local fits = existing and (if className == "ModuleScript"
		then existing:IsA("ModuleScript")
		else existing:IsA("BaseScript"))
	if existing and not fits then
		existing.Name = name .. "_Old"
		table.insert(log, "renamed unexpected " .. existing.ClassName .. " to " .. existing:GetFullName())
		existing = nil
	end
	local script = existing or Instance.new(className)
	script.Name = name
	script.Source = source
	script.Parent = parent
	table.insert(log, (existing and "updated " or "created ") .. script:GetFullName())
end

local combat = folder(ReplicatedStorage, "Combat")
local remotes = folder(combat, "Remotes")
for _, name in ipairs({ "Ack", "Action", "Anim", "Effect", "Impulse" }) do
	if not remotes:FindFirstChild(name) then
		local remote = Instance.new("RemoteEvent")
		remote.Name = name
		remote.Parent = remotes
		table.insert(log, "created " .. remote:GetFullName())
	end
end

-- Server scripts stay wherever CombatService lives (they require each other
-- as siblings); the client stays wherever CombatClient lives.
local existingService = ServerScriptService:FindFirstChild("CombatService", true)
local serverHome = existingService and existingService.Parent or ServerScriptService
local existingClient = StarterPlayer:FindFirstChild("CombatClient", true)
local clientHome = existingClient and existingClient.Parent
	or StarterPlayer:FindFirstChildOfClass("StarterPlayerScripts")
	or StarterPlayer:WaitForChild("StarterPlayerScripts")
local HOMES = { combat = combat, server = serverHome, client = clientHome }

for _, entry in ipairs(SCRIPTS) do
	put(HOMES[entry.home], entry.class, entry.name, SOURCES[entry.name])
end

-- The MMORPG HUD is retired.
local hud = combat:FindFirstChild("HUD")
if hud then
	hud:Destroy()
	table.insert(log, "removed ReplicatedStorage.Combat.HUD")
end

if recording then
	ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
else
	pcall(function()
		ChangeHistoryService:SetWaypoint("Install combat rework")
	end)
end

print("Combat rework installed:")
for _, line in ipairs(log) do
	print("  " .. line)
end
'''


def delimiter(sources):
    level = 3
    while any(("]" + "=" * level + "]") in s for s in sources):
        level += 1
    return "=" * level


def main():
    texts = []
    for name, cls, home, path in SCRIPTS:
        with open(os.path.join(SRC, path)) as f:
            texts.append((name, cls, home, f.read()))
    eq = delimiter([t[3] for t in texts])
    parts = [HEADER]
    for name, _, _, text in texts:
        # a long bracket drops a leading newline, so add one to keep line 1 intact
        parts.append(f"\nSOURCES.{name} = [{eq}[\n{text}]{eq}]\n")
    table = "\n".join(f'\t{{ name = "{n}", class = "{c}", home = "{h}" }},' for n, c, h, _ in texts)
    parts.append(BODY % table)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("".join(parts))
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
